### ISSUE TITLE
Consumer Switch to Stream Failed

### ISSUE THREAD

**Issue by aollag09** [SourceLabOrg/kafka-webview#127]
Hello

Got the following Stack Trace when I try to switch to the stream view. The browser view is working fine !
And if I try to logout from my default user, I got the Error 500 Houston, we have a problem :) !

Thanks for your help

`2019-01-15 16:46:08.816 ERROR 33528 --- [oundChannel-109] .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

java.lang.NullPointerException: null
        at org.sourcelab.kafka.webview.ui.controller.stream.StreamController.getLoggedInUser(StreamController.java:189) ~[classes!/:2.1.2]
        at org.sourcelab.kafka.webview.ui.controller.stream.StreamController.getLoggedInUserId(StreamController.java:182) ~[classes!/:2.1.2]
        at org.sourcelab.kafka.webview.ui.controller.stream.StreamController.newConsumer(StreamController.java:130) ~[classes!/:2.1.2]
        at org.sourcelab.kafka.webview.ui.controller.stream.StreamController$$FastClassBySpringCGLIB$$9d63246f.invoke(<generated>) ~[classes!/:2.1.2]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) ~[spring-aop-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.sourcelab.kafka.webview.ui.controller.stream.StreamController$$EnhancerBySpringCGLIB$$65d5c314.newConsumer(<generated>) ~[classes!/:2.1.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181) ~[spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114) ~[spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:517) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:495) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:88) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:475) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:411) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:138) [spring-messaging-5.0.12.RELEASE.jar!/:5.0.12.RELEASE]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
`

**Comment by Crim** [comment]
Hello @aollag09 ,

Which authentication method are you using?  Just the default with users created within the application?  Or are you using anonymous authentication?

It looks like I can reproduce this reliably when using anonymous authentication.  Let me play around and work out what exactly is going on.

**Comment by aollag09** [comment]
Hello
Yes I'm using the anonymous authentication. And I can't logout

**Comment by Crim** [comment]
I believe that I've committed a fix for this.  I'll need to release a new version in the next day or so.

Thanks for reporting the issue!

**Comment by Crim** [comment]
Cut a new release (2.1.3) If you continue to have problems please reopen the issue.

Thanks
